package br.com.dfdevforge.common.services;

import java.util.Map;

public interface CommonService {
	default Map<String, Object> execute() throws Exception {
		this.validateUserAccess();
		this.executeBusinessRule();
		this.configureUserActions();

		return this.returnBusinessData();
	}

	/**
	 * Its purpose is to validate user access before executing the business rule.
	 */
	public void validateUserAccess();

	/**
	 * Its purpose is to group all necessary methods to business rule execution.
	 * @throws Exception 
	 */
	public void executeBusinessRule() throws Exception;

	/**
	 * Its purpose is to group all necessary methods to configure the visibility of user components.
	 */
	public void configureUserActions();

	/**
	 * Its purpose is to group all content generated by the business rule and return it to the controller layer.
	 * 
	 * @return Map<String, Object>
	 */
	public Map<String, Object> returnBusinessData();

}
