version: "3.3"

services:
  sisfin-maintenance:
    build: ../sisfin-maintenance/
    image: img_sisfin_maintenance_dev:0.1
    container_name: con_sisfin_maintenance_dev  
    restart: always
    env_file:
      - ../sisfin-config/sisfin-backend.env
    ports:
      - 8080:8080
    networks:
      - net_sisfin_dev

networks:
  net_sisfin_dev:
    name: net_sisfin_dev